### ISSUE TITLE
Alternating signs - lab07

### ISSUE THREAD

**Issue by Aghavali9** [sharkmate/polito_cs_labs#1]
- user input is not sanitized, a sudden enter breaks the code.
- inputs **1, 2, 3 returns -2** instead of **2**

**Comment by sharkmate** [comment]
the user input is not sanitized indeed, but the result you get is right, with 1 and 3 having even indexes [0, 2] and 2 odd [1]

**Comment by sharkmate** [comment]
true i got a lil coonfused with sums as an engineering student always nice to see that thanks
